import Head from "next/head";
import Profile from "../../components/advocates/Profile";
import Layout from "../../components/layout/Layout";

export const getServerSideProps = async ({ params }) => {
  const otherRes = await fetch(`https://cados.up.railway.app/advocates`);

  const res = await fetch(
    `https://cados.up.railway.app/advocates/${params.user}`
  );

  const userData = await res.json();
  const otherData = await otherRes.json();

  return {
    props: {
      user: userData.advocate,
      otherData: otherData.advocates,
    },
  };
};

function User({ user, otherData }) {
  return (
    <>
      <Head>
        <title>{user.username} - Cados dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Profile user={user} others={otherData} />
      </Layout>
    </>
  );
}

export default User;
