import Head from "next/head";
import Layout from "../../components/layout/Layout";
import Img from "../../components/tools/Img";

export const getServerSideProps = async ({ params }) => {
  const res = await fetch(
    `https://cados.up.railway.app/advocates?query=${params.user}`
  );
  const userData = await res.json();
  return {
    props: {
      user: userData.advocates[0],
    },
  };
};

function User({ user }) {
  //   console.log(user);
  return (
    <>
      <Head>
        <title>{user.username} - Cados dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className="container py-32">
          <div className="w-[300px] h-[300px] overflow-hidden rounded-full">
            <Img src={user.profile_pic} alt={user.name} />
          </div>

          <h1>{user.name}</h1>
          <p>@{user.username}</p>
          <p>{user.bio}</p>
        </section>
      </Layout>
    </>
  );
}

export default User;
