import Head from "next/head";
import Link from "next/link";
// import { useRouter } from "next/router";
import Landing from "../../components/advocates/Landing";
import Layout from "../../components/layout/Layout";
import Img from "../../components/tools/Img";

export const getStaticProps = async () => {
  const res = await fetch("https://cados.up.railway.app/advocates?limit=8");
  const userData = await res.json();
  return {
    props: {
      user: userData.advocates,
    },
    revalidate: 10,
  };
};

function advocates({ user }) {
  return (
    <>
      <Head>
        <title>Discover peoples - Cados dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Landing />
        <section className="container py-16 overflow-hidden">
          <div className="grid grid-cols-4 gap-4">
            {user.map((dev) => (
              <Link
                href={`advocates/${dev.username.toLowerCase()}`}
                key={dev.username}
              >
                <a className="text-center space-y-3">
                  <div className="w-full h-[200px] overflow-hidden rounded-full">
                    <Img src={dev.profile_pic} alt={dev.name} />
                  </div>

                  <p>{dev.username}</p>
                </a>
              </Link>
            ))}
          </div>
        </section>
      </Layout>
    </>
  );
}

export default advocates;
