import Head from "next/head";
import AdvocateList from "../components/home/AdvocateList";
import Landing from "../components/home/Landing";
import Layout from "../components/layout/Layout";

export const getStaticProps = async () => {
  const res = await fetch("https://cados.up.railway.app/advocates/");
  const userData = await res.json();
  return {
    props: {
      user: userData.advocates,
    },
    revalidate: 10,
  };
};

export default function Home({ user }) {
  // console.log(user);
  return (
    <>
      <Head>
        <title>Cados dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Landing />
        <AdvocateList data={user} />
      </Layout>
    </>
  );
}
