import Head from "next/head";
import Layout from "../components/layout/Layout";

function register() {
  return (
    <>
      <Head>
        <title>Register - Cados dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>Register</h1>
      </Layout>
    </>
  );
}

export default register;
