import Head from "next/head";
import Layout from "../components/layout/Layout";
import Search from "../components/search/Search";

export const getServerSideProps = async ({ query }) => {
  const { keyword, page = 1 } = query;
  const res = await fetch(
    `https://cados.up.railway.app/advocates?query=${keyword}&page=${page}&limit=20`
  );
  const userData = await res.json();
  if (!userData) {
    return {
      redirect: "/",
      parmanent: false,
    };
  }
  return {
    props: {
      pagination: userData.pagination,
      user: userData.advocates,
    },
  };
};

function search({ user, pagination }) {
  return (
    <>
      <Head>
        <title>Find your peers - Cados dev</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <Search user={user} pagination={pagination} />
      </Layout>
    </>
  );
}

export default search;
