import Head from "next/head";
import Layout from "../components/layout/Layout";

function search() {
  return (
    <>
      <Head>
        <title>Search - Cados dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        
      </Layout>
    </>
  );
}

export default search;
